### ISSUE TITLE
Action fails with `error Command "npm" not found.`

### ISSUE THREAD

**Issue by gotson** [c2corg/browserslist-update-action#1126]
I am trying to use the action on my project here: https://github.com/gotson/komga-website/actions/runs/11623523702/job/32370686097

It seems this was raised before in #69 but i don't see any mention of `yarn` in the code, so i'm wondering if it is supposed to work or not.

My workflow file is here: https://github.com/gotson/komga-website/blob/master/.github/workflows/browserlist-update.yml

Am i missing some config in my workflow file, or is this not supported ?

**Comment by brunobesson** [comment]
Hi, and sorry for the late answer. Indeed, the command that is run is `npx update-browserslist-db@latest`, so yarn is not supported currently.

However, i should be fairly easy to add. I am now yarn user, is `yarn dlx` the corresponding command?

**Comment by gotson** [comment]
> I am now yarn user, is `yarn dlx` the corresponding command?

i'm not even sure myself

**Comment by brunobesson** [comment]
I released v2.5.0 which should handle other package managers. Let me know whether it works or you encounter issues.

**Comment by gotson** [comment]
thanks!

I'm using `c2corg/browserslist-update-action@v2` in my action, which should point to v2.5 from what i see, but it still fails: https://github.com/gotson/komga-website/actions/runs/11965908470/job/33360702651

**Comment by brunobesson** [comment]
According to https://github.com/antfu-collective/package-manager-detector/blob/main/src/commands.ts (which is the library I used to detec package manager), yarn berry (2+) should indeed use yarn dlx

![image](https://github.com/user-attachments/assets/6609fcba-9752-4b6f-80aa-a15fd02100ee)

I'll try to provide you a test version with some debug output.

**Comment by brunobesson** [comment]
Also, could you try with an explicit `v2.5.0 `version?

**Comment by gotson** [comment]
> Also, could you try with an explicit `v2.5.0 `version?

Just tried but still the same issue https://github.com/gotson/komga-website/actions/runs/12001951497/job/33453189993

**Comment by gotson** [comment]
Just a heads up that i migrated my project to `npm`. Somehow i used `yarn` because the project samples were using `yarn`, but after checking again the project also supports `npm`, so i switched to that because i am more familiar with it.

Feel free to close this ticket, as i won't be monitoring it myself since i don't need it anymore. Thanks for the great work on this project!
